POST http://localhost:4000/user/register
Content-Type: application/json

{
  "fullname" : "Ram bahadur neupane",
  "email" : "rambahadur@gmail.com",
  "password" : "rambahadur@123"
}

###
POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email" : "rambahadur@gmail.com",
  "password" : "rambahadur@123"
}

###
GET http://localhost:4000/user/getProfile/698ada508ef4daef4a29a239
