POST http://localhost:4000/captain/create
Content-Type: application/json

{
  "fullname": "Ram Bahadur",
  "email": "ram@gmail.com",
  "password": "securePassword123",
  "color": "Black",
  "plate": "BA-2-PA-1234",
  "capacity": 4,
  "vehicleType": "car"
}
